version: '3'

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000

  jenkins:
    image: jenkinsci/blueocean:latest
    container_name: jenkins
    restart: always
    depends_on:
      - portainer
    user: "1000:0"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9001:8080
    environment:
      - JAVA_OPTS=-Dhudson:footerURL=https://jenkins.example.com

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: always
    depends_on:
      - portainer
    volumes:
      - nexus_home:/nexus-data
    ports:
      - 9002:8081
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms2g -Xmx2g -XX:MaxDirectMemorySize=3g

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: CHANGEME

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 9003:8080

volumes:
  jenkins_home:
  nexus_home:
  portainer_data:
  mariadb_data: